defaults:
  - algo: ???

global_seed: 123
spatial_train_test_split:
  init_frac: 0.05
  levels: 1
  buffer: 1
  seed: 0

algo:  # these config must be overwritten by algo/*.yaml
  needs_train_test_split: true
  name: ${hydra:runtime.choices.algo}

  method:
    _target_: ???  # most point to a spacebench.algorithms.SpatialMethod calss
  binary: ???
  continuous: ???

  tune:  # ray tune resources, can override  in algo/*.yaml but not needed
    param_space: {}
    resources:
      cpu: 1
    tune_config:
      _target_: ray.tune.TuneConfig
      num_samples: 50
      max_concurrent_trials: 4
      scheduler:
        _target_: ray.tune.schedulers.ASHAScheduler
      mode: min
    run_config:
      _target_: ray.air.RunConfig
      local_dir: benchmarks/ray
      name: ${hydra:runtime.choices.algo}
