needs_train_test_split: false

method:
  _target_: spacebench.algorithms.SpatialPlus
  max_iter: 2_500
  spatial_split_kwargs:
    init_frac: 0.02
    levels: 1
    seed: 0
  k: 100

tune:
  param_space:
    lam_t:
      _target_: ray.tune.loguniform
      _args_: [1e-5, 1.0]
    lam_y:
      _target_: ray.tune.loguniform
      _args_: [1e-5, 1.0]

