needs_train_test_split: true

method:
  _target_: spacebench.algorithms.SpatialPlus
  max_iter: 5_000

tune:
  param_space:
    k:
      _target_: ray.tune.choice
      _args_:
        - [100, 500]
    lam_t:
      _target_: ray.tune.loguniform
      _args_: [1e-8, 0.5]
    lam_y:
      _target_: ray.tune.loguniform
      _args_: [1e-8, 0.5]

  num_samples: 10