name: benchmarks
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch
  - torchvision
  - pip
  - pip:
    - torch_geometric
    - jsonlines>=3.1
    - xgboost>=1.7.4
    - torchmetrics>=0.11.4
    - pysal>=2.5.0
    - scikit-learn>=1.2.2
    - pytorch-lightning>=2.0.2
    - matplotlib>=3.4.3
    - seaborn>=0.11.2
    - hydra-core>=1.3.0
    - pandas>=1.5.3
    - pyDataverse>=0.3.1
    - requests>=2.28.1
    - setuptools>=58.0.4
    - networkx>=3.0
    - pyproj==3.4.1
    - urllib3>=1.26.11
    - pyyaml>=6.0
    - tqdm>=4.62.3
    - scipy>=1.10.1
    - "ray[tune]"==2.6.3
    - optuna==3.3.0
