name: Python package dist

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup conda
      uses: s-weigand/setup-conda@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        conda update --all
        conda install -c intel mkl_random
        conda install -c intel mkl_fft
        conda config --append channels conda-forge
        conda config --append channels intel
        conda install -y mkl-service
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Create Distribution Bundle
      run: |
        python setup.py sdist
        ls -l dist

    - name: Install package from dist
      run: |
        cd dist
        tar zxvf *.tar.gz --one-top-level
        cd $(ls -d */)
        echo "Current directory: $(pwd)"
        echo "Directory contents: $(ls -l)"
        pip install .

    - name: Test with pytest
      run: |
        pip install coverage
        coverage run -m pytest tests/
        coverage report -i
        coverage xml -i

